import { ConvexClientProvider } from '@/components/providers/convex-client-provider';
import { Toaster } from '@/components/ui/sonner';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from './provider';

const font = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Prompt Forge',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ConvexClientProvider>
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
