import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Header } from '@/components/custom/header';
import { MessagesContext } from '@/context/messages-context';
import { MessagesProvider } from '@/components/providers/messages-provider';
import { UserDetailsProvider } from '@/components/providers/user-details-provider';
import { AuthProvider } from '@/components/providers/auth-provider';
import { ConvexClientProvider } from '@/components/providers/convex-client-provider';

const font = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ConvexClientProvider>
          <UserDetailsProvider>
            <AuthProvider>
              <MessagesProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="dark"
                  enableSystem={false}
                  disableTransitionOnChange
                >
                  <Header />
                  {children}
                </ThemeProvider>
              </MessagesProvider>
            </AuthProvider>
          </UserDetailsProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
